import 'package:swf_app/src/catalog/models/book.dart';

const List<Book> sampleBooks = [
  Book(
    id: '1',
    title: 'The Ember Throne',
    authorName: 'Ariadne Voss',
    description:
        'A disgraced fire mage must reclaim her power to stop an ancient evil from consuming the Five Kingdoms.',
    imageUrl: '',
    subgenres: ['Epic Fantasy', 'High Fantasy'],
    tropes: ['Chosen One', 'Revenge Quest', 'Morally Grey'],
    spiceLevel: SpiceLevel.medium,
    ageCategory: 'Adult',
    representations: ['BIPOC'],
    languageLevel: LanguageLevel.moderate,
    kindleUnlimited: true,
    hasAudiobook: true,
  ),
  Book(
    id: '2',
    title: 'Shadows of the Fae Court',
    authorName: 'Liora Mendez',
    description:
        'When a mortal woman stumbles into the fae realm, she finds herself caught between two rival courts—and two dangerously alluring princes.',
    imageUrl: '',
    subgenres: ['Romantic Fantasy'],
    tropes: ['Enemies to Lovers', 'Forbidden Love', 'Fated Mates'],
    spiceLevel: SpiceLevel.hot,
    ageCategory: 'Adult',
    representations: ['LGBTQ+'],
    languageLevel: LanguageLevel.moderate,
    kindleUnlimited: true,
  ),
  Book(
    id: '3',
    title: 'The Witch of Briarhollow',
    authorName: 'Tansy Fairbrook',
    description:
        'A cozy tale of a hedge witch who opens a potions shop in a magical village, only to uncover a century-old curse.',
    imageUrl: '',
    subgenres: ['Cozy Fantasy'],
    tropes: ['Found Family', 'Slow Burn'],
    spiceLevel: SpiceLevel.none,
    ageCategory: 'Young Adult',
    languageLevel: LanguageLevel.clean,
    hasAudiobook: true,
  ),
  Book(
    id: '4',
    title: 'Blood & Iron Covenant',
    authorName: 'Ren Blackthorn',
    description:
        'In a city where magic is outlawed, a thief and an inquisitor form an uneasy alliance to pull off the heist of the century.',
    imageUrl: '',
    subgenres: ['Dark Fantasy', 'Urban Fantasy'],
    tropes: ['Anti-Hero', 'Heist', 'Forced Proximity'],
    spiceLevel: SpiceLevel.mild,
    ageCategory: 'Adult',
    representations: ['BIPOC', 'Disability'],
    languageLevel: LanguageLevel.strong,
  ),
  Book(
    id: '5',
    title: 'Starfall Academy',
    authorName: 'Celeste Amari',
    description:
        'At an elite academy for gifted mages, a scholarship student discovers a conspiracy that threatens to tear the school apart.',
    imageUrl: '',
    subgenres: ['High Fantasy'],
    tropes: ['Magic Academy', 'Hidden Royalty', 'Slow Burn'],
    spiceLevel: SpiceLevel.mild,
    ageCategory: 'New Adult',
    representations: ['Neurodivergent'],
    languageLevel: LanguageLevel.mild,
    kindleUnlimited: true,
    hasAudiobook: true,
  ),
  Book(
    id: '6',
    title: 'The Serpent God\'s Bride',
    authorName: 'Nalini Dhar',
    description:
        'A priestess is chosen as a sacrifice to the serpent god—but he wants a queen, not a victim.',
    imageUrl: '',
    subgenres: ['Mythological Fantasy', 'Romantic Fantasy'],
    tropes: ['Fated Mates', 'Forbidden Love', 'Enemies to Lovers'],
    spiceLevel: SpiceLevel.scorching,
    ageCategory: 'Adult',
    representations: ['BIPOC'],
    languageLevel: LanguageLevel.strong,
  ),
  Book(
    id: '7',
    title: 'Blades of the Broken Realm',
    authorName: 'Kai Ashford',
    description:
        'A wandering swordsman and a disgraced knight cross paths on a quest to find a legendary weapon before a warlord does.',
    imageUrl: '',
    subgenres: ['Sword & Sorcery', 'Epic Fantasy'],
    tropes: ['Quest Narrative', 'Morally Grey', 'Found Family'],
    spiceLevel: SpiceLevel.none,
    ageCategory: 'Young Adult',
    languageLevel: LanguageLevel.mild,
    hasAudiobook: true,
  ),
  Book(
    id: '8',
    title: 'The Door Between Worlds',
    authorName: 'Mira Chen',
    description:
        'A teenager discovers a portal in her grandmother\'s attic that leads to a dying world only she can save.',
    imageUrl: '',
    subgenres: ['Portal Fantasy'],
    tropes: ['Chosen One', 'Prophecy', 'Found Family'],
    spiceLevel: SpiceLevel.none,
    ageCategory: 'Young Adult',
    representations: ['BIPOC', 'Neurodivergent'],
    languageLevel: LanguageLevel.clean,
    kindleUnlimited: true,
  ),
  Book(
    id: '9',
    title: 'Nightshade & Nectar',
    authorName: 'Vivienne Drake',
    description:
        'Two rival potion brewers are forced to share a shop—and sparks fly in more ways than one.',
    imageUrl: '',
    subgenres: ['Cozy Fantasy', 'Romantic Fantasy'],
    tropes: ['Enemies to Lovers', 'Forced Proximity', 'Slow Burn'],
    spiceLevel: SpiceLevel.medium,
    ageCategory: 'New Adult',
    representations: ['LGBTQ+'],
    languageLevel: LanguageLevel.mild,
    kindleUnlimited: true,
    hasAudiobook: true,
  ),
  Book(
    id: '10',
    title: 'Ashen Prophecy',
    authorName: 'Dorian Hale',
    description:
        'An oracle who can see the future but never her own must navigate court politics to prevent a devastating war.',
    imageUrl: '',
    subgenres: ['High Fantasy', 'Dark Fantasy'],
    tropes: ['Prophecy', 'Hidden Royalty', 'Anti-Hero'],
    spiceLevel: SpiceLevel.hot,
    ageCategory: 'Adult',
    representations: ['Disability'],
    languageLevel: LanguageLevel.moderate,
    hasAudiobook: true,
  ),
  Book(
    id: '11',
    title: 'The Wolf King\'s Bargain',
    authorName: 'Seraphina Wolfe',
    description:
        'A healer strikes a deal with a cursed shifter king: break his curse, and he will free her village.',
    imageUrl: '',
    subgenres: ['Romantic Fantasy', 'Dark Fantasy'],
    tropes: ['Fated Mates', 'Morally Grey', 'Slow Burn'],
    spiceLevel: SpiceLevel.scorching,
    ageCategory: 'Adult',
    languageLevel: LanguageLevel.strong,
    kindleUnlimited: true,
  ),
  Book(
    id: '12',
    title: 'Thieves of Sunken Loria',
    authorName: 'Jasper Thorne',
    description:
        'A ragtag crew of outcasts plans to rob the treasure vault of a drowned city guarded by sea monsters.',
    imageUrl: '',
    subgenres: ['Sword & Sorcery', 'Low Fantasy'],
    tropes: ['Heist', 'Found Family', 'Quest Narrative'],
    spiceLevel: SpiceLevel.mild,
    ageCategory: 'Adult',
    representations: ['LGBTQ+', 'BIPOC'],
    languageLevel: LanguageLevel.moderate,
    hasAudiobook: true,
  ),
];
